# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [4]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 37 ms
Wall time: 1.49 s


### Exercício 2

In [5]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[5:8] = 0
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [7]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [9]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Imprima os elementos da terceira linha da matriz
arr2d[2]

array([7, 8, 9])

In [11]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

### Exercício 5

In [12]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [14]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [15]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [16]:
resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

### Exercício 7

In [17]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
A = np.arange(10)
print(A)
np.save('array_a', A)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [19]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [20]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [21]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [22]:
data = resp.json()
data[0]['title']

'Memory issues with `multiprocessing` and GroupBy on multiindex DataFrame'

In [23]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    22401  Memory issues with `multiprocessing` and Group...   
1    22400  assert_series_equal(..., check_exact=True) rep...   
2    22399                                   Progress bar gbq   
3    22398  DOC: html build of class docstrings without au...   
4    22397                   Make Series.shift always a copy?   
5    22396                              CircleCI 2.0 followup   
6    22395  DOC: add pd.set_eng_float_format function in t...   
7    22394  Bug in DataFrame.drop_duplicates for empty Dat...   
8    22393                    Suggestion: implement Q-Q plots   
9    22390      Fix arithmetic errors with timedelta64 dtypes   
10   22389          Series[sparse].to_sparse messes up length   
11   22388                  Make EAs for all Block subclasses   
12   22387                     Support NDFrame.shift with EAs   
13   22386                 Support ExtensionArrarys for shift   
14   22385                 Mean and std for float32 dataframe   
15   22384         API: astype mechanism for extension arrays   
16   22383  .ne fails with abiguous message if comparing a...   
17   22382                                   WIP: EA SetArray   
18   22381          CategoricalBlock.array_dtype out of date?   
19   22380      BUG: fix read_csv to parse timezone correctly   
20   22378  Fix and test scalar extension dtype op corner ...   
21   22377  BUG: Fix DataFrame.apply for string arg with a...   
22   22376  DataFrame.apply fails for string function argu...   
23   22375  ENH: Enable DataFrame.corrwith to compute rank...   
24   22374                   Silent Failure with Partial Rows   
25   22373  version 0.23: RangeIndex argument order change...   
26   22372  Using df.at() for assignment changes views of ...   
27   22369                        CLN: Simplify Block._astype   
28   22367    DataFrame.__setitem__ is broken for SparseArray   
29   22365                   Resampler.__iter__() not working   

                                               labels state  
0                                                  []  open  
1                                                  []  open  
2   [{'id': 57351315, 'node_id': 'MDU6TGFiZWw1NzM1...  open  
3   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
4   [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
5                                                  []  open  
6   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
7   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
8   [{'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk...  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10  [{'id': 49182326, 'node_id': 'MDU6TGFiZWw0OTE4...  open  
11  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open  
12  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open  
13  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open  
14  [{'id': 527603109, 'node_id': 'MDU6TGFiZWw1Mjc...  open  
15  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open  
18  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open  
19  [{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
24  [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open  
25                                                 []  open  
26  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
27  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
28  [{'id': 49182326, 'node_id': 'MDU6TGFiZWw0OTE4...  open  
29  [{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...  open

### Exercício 10

In [21]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [22]:
data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [23]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [24]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5

# Fim

### Obrigado - Data Science Academy - <a href=http://facebook.com/dsacademy>facebook.com/dsacademybr</a>